// CATEGORIES Action Types
export const CATEGORY_LOADED = 'CATEGORY_LOADED';

// POSTS Action Types
export const POST_ADDED = 'POST_ADDED';
export const POST_LOADED = 'POST_LOADED';
export const POST_SORTED = 'POST_SORTED';
export const POST_FOUND = 'POST_FOUND';
export const POST_FOUND_BY_CATEGORY = 'POST_FOUND_BY_CATEGORY';
export const POST_VOTE_UPDATED = 'POST_VOTE_UPDATED';
export const POST_UPDATED = 'POST_UPDATED';
export const POST_DELETED = 'POST_DELETED';

// COMMENTS Action Types
export const COMMENTS_LOADED = 'COMMENTS_LOADED';
export const COMMENT_ADDED = 'COMMENT_ADDED';
export const COMMENT_VOTE_UPDATED = 'COMMENT_VOTE_UPDATED';
export const COMMENT_UPDATED = 'COMMENT_UPDATED';
export const COMMENT_DELETED_SINGLE = 'COMMENT_DELETED_SINGLE';
export const COMMENT_DELETED_ALL = 'COMMENT_DELETED_ALL';
